# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
    config.vm.define "ubuntu20desk" do |config|
      config.vm.box = "fasmat/ubuntu2004-desktop"
      config.vm.hostname = "ubuntu20desk"
      config.vm.provider "vmware_desktop" do |v|
        v.gui = true
        v.vmx["memsize"] = "4092"
        v.vmx["numvcpus"] = "2"
      end
    end
end